version: '3.8'

services:
  db:
    image: mysql
    container_name: mysql_local
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: test_db
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  my-db:
